insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('Wasim','Akhtar','wsurpliss0', 'g47Al7q', 'Admin', 'cboyland0@home.pl', 'Amazon', 'US','Placentia', 1, null, '442-414-9070', '7a087e9b4f9e3b05133a686ff5f973554fffe70b5c18bdfcfae57af13539e41b');
insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('Sellick','Fernandes','sellick1', '998lM6Id', 'Admin', 'sgreenhall1@chicagotribune.com', 'Gigazoom', 'US','Anaheim', 1, null, '192-339-1716', '08f626d2d7bfc26507d84ac343d33e36cfd7bc4ca0b4f84e8cbc9f0060fa3807');
insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('George','Omelley','gmellenby2', 'qFgqzs', 'Admin', 'wfibbens2@aol.com', 'Eare', 'US','San Deigo', 1, null, '510-548-4821', '9cb9bdb5e8105382509e390084c757575725f3c26c630e70d4c7551116420fea');
insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('Zack','Bert','zalberts3', 'zuIlxF', 'Manager', 'gszreter3@xinhuanet.com', 'Tommy Hilfiger', 'US','Placentia', 1, null, '739-264-6834', 'f68295e3b129d19db5693258d5c6a9d66945a9129a4494db34d5c458233367f9');
insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('Rachel','John','rsparway4', 'b8MtGin2', 'Manager', 'tdouch4@sciencedirect.com', 'Quamba', 'US','Placentia', 1, null, '195-730-8737', '3d6a9088ace0b492901621b6e6b668bcfcc09ef084226c70df74efab7a67f534');
insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('Derek','MElley','dmetrick6', '7YmgnCRCDL4', 'Admin', 'cdoorbar6@typepad.com', 'Wikivu', 'US','Placentia', 0, null, '478-666-3847', '5f3718f049e1b8d550a3c82c0bfcb3143dd5783f9a2dc94285030669e3c739d5');
insert into user (firstname, lastname, username, password, accesslevel, email, company, country, location, isActive, profilepicture, contactno, hashkey) values ('PAterson','Burke','bparsonson7', '60Id5QZu7qk', 'Manager', 'dbawdon7@ebay.com', 'Photofeed', 'US','Placentia', 0, null, '793-859-6959', '85e147babeba810f1feb657f3055d56eb4b1334b35a814bec8ce3db563aa7ad5');


insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('1','electronics','94','California','wsurpliss0','bparsonson7','United States','Amazon');
insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('2','clothing','91','Washington','gmellenby2','wsurpliss0','UK','Tommy Hilfiger');
insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('3','education','9','Texas','zalberts3','dmetrick6','India','Wikivu');
insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('4','grocery','94','Michigan','sellick1','zalberts3','Unites States','Quamba');
insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('5','medicines','91','Oklahoma','rsparway4','gmellenby2','Mexico','Eare');
insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('6','media','10','Nevada','bparsonson7','dmetrick6','Canada','Photofeed');
insert into inventory (inventoryid,inventoryname,numberofitems,location,createdby,lastupdatedby,country,company)values ('7','accessories','94','California','sellick1','zalberts3','Germany','Gigazoom');



INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('1','7','Beats By Dr.Dre Headset','Features the iconic Beats sound with Dual-Mode Adaptive Noise Canceling, plus the added benefit of wireless listening.Pair and Play with your Bluetooth device with 30ft range.','electronic accessories','100','California','numberOfItems','300','In Stock','1-01-17','10-11-20','sellick1','zalberts3','Gigazoom','50')
INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('2','1','Samsung UHD TV','QLED TV.Samsungs Innovation TV. Discover perfect color the Samsung QLED TV, enjoy a billion more colors HD.','electronics','200','California','numberOfItems','500','In Stock','1-01-17','10-11-20','wsurpliss0','bparsonson7','Amazon','10')
INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('3','3','Apple Laptop Macbook Pro','Educational Laptop by Apple Inc.','education','500','Texas','numberOfItems','50','In Stock','1-01-17','10-11-20','zalberts3','dmetrick6','Wikivu','20')
INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('4','2','Men Suits','Men Suits','clothing','150','Washington','numberOfItems','50','In Stock','1-01-17','10-11-20','gmellenby2','wsurpliss0','Tommy Hilfiger', '10')
INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('5','4','Daily Grocery','Grocery package for daily use','grocery','100','Michigan','numberOfItems','20','In Stock','1-01-17','10-11-20','sellick1','zalberts3','Quamba', '5')
INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('5','6','Netflix videos','All 2017 videos by Netflix','media','300','Nevada','numberOfItems','60','In Stock','1-01-17','10-11-20','bparsonson7','dmetrick6','Photofeed', '10')
INSERT INTO inventoryitem (itemid,inventoryid,itemname,Description,itemgroup,quantity,Location,unitofmeasure,costperunit,status,createddate,Expirationdate,createdBy,lastUpdatedBy,company, Initial_Quantity) values ('5','5','Medicine CIuY80','Flu Medicine','medicines','500','Oklahoma','numberOfItems','10','In Stock','1-01-17','10-11-20','rsparway4','wsurpliss0','Eare', '5')
